name: build

on:
  push:
    branches: [ master ]
  pull_request_target:
    branches: [ master ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.14, 1.15]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: setup go ${{ matrix.go-version }}
      uses: actions/setup-go@v2.1.2
      with:
        go-version: ${{ matrix.go-version }}
    - name: check out code
      uses: actions/checkout@v2.3.3
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.head_ref }}
    - uses: actions/cache@v2.1.1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          ${{ runner.os }}-go-${{ matrix.go-version }}-
    - name: test
      run: go test -v -race -coverprofile="coverage.txt" -covermode=atomic ./...
    - name: uploading coverage to codecov
      uses: codecov/codecov-action@v1.0.13
      with:
        name: golang ${{ matrix.go-version }} on ${{ runner.os }}
