name: fossa

on:
  push:
    branches: [ master ]
  pull_request_target:
    branches: [ master ]

jobs:
  fossa:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.15]
        os: [ubuntu-latest]
    defaults:
      run:
        shell: bash
    steps:
    - name: check out code
      uses: actions/checkout@v2.3.2
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.head_ref }}
    - name: setup go ${{ matrix.go-version }}
      uses: actions/setup-go@v2.1.2
      with:
        go-version: ${{ matrix.go-version }}
      env:
        GOPATH: /root/go
    - uses: oprypin/find-latest-tag@v1
      with:
        repository: fossas/fossa-cli
      id: tag
    - uses: actions/cache@v2.1.1
      id: cache
      with:
        path: /usr/local/bin/fossa
        key: ${{ matrix.go-version }}-${{ steps.tag.outputs.tag }}
        restore-keys: |
          ${{ matrix.go-version }}-${{ steps.fossa.outputs.tag }}
          ${{ matrix.go-version }}
    - name: install fossa
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      run: |
        sudo mkdir -pv $GOPATH/pkg
        sudo mkdir -pv $GOBIN
        sudo mkdir -pv $GOPATH/src/github.com/$GITHUB_REPOSITORY
        curl https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
        sudo chown -R $(id -u) /usr/local/bin/fossa
      env:
        GOPATH: /root/go
        GOBIN: /root/go/bin
    - name: build
      run: go build -mod=readonly
      env:
        GOPATH: /root/go
        GOBIN: /root/go/bin
    - name: analyze
      run: fossa analyze --no-ansi --revision ${{ github.sha }}
      env:
        FOSSA_API_KEY: ${{ secrets.FOSSA_PUSH }}
        GOPATH: /root/go
        GOBIN: /root/go/bin
    - name: check results
      run: fossa test --no-ansi --revision ${{ github.sha }}
      env:
        FOSSA_API_KEY: ${{ secrets.FOSSA_PUSH }}
        GOPATH: /root/go
        GOBIN: /root/go/bin
    - name: generate reports
      run: |
        fossa report dependencies --no-ansi --revision ${{ github.sha }} --output-file dependencies.md
        fossa report licenses --no-ansi --revision ${{ github.sha }} --output-file licenses.md
      env:
        FOSSA_API_KEY: ${{ secrets.FOSSA_ELEVATED }}
        GOPATH: /root/go
        GOBIN: /root/go/bin
    - uses: actions/upload-artifact@v2.1.4
      with:
        name: report
        path: |
          dependencies.md
          licenses.md
  docs:
    name: update docs
    needs: fossa
    if: ${{ github.head_ref == '' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2.3.2
        with:
          ref: gh-pages
      - uses: actions/download-artifact@v2.0.5
        with:
          name: report
      - name: committing changed files
        uses: stefanzweifel/git-auto-commit-action@v4.4.1
        with:
          commit_user_name: ${{ github.event.pusher.name }}
          commit_user_email: ${{ github.event.pusher.email }}
          commit_message: |
            docs: update license report
            this update was initiated by commit ${{ github.sha }}
          file_pattern: '*.md'
